TTS:
  output_dir: tmp/tts/
  index_tts:
    config: checkpoints/checkpoints-config.yaml
  edge_tts:
    config: configs/edge-tts.yaml
ASR:
  FunASR:
    model: paraformer-zh-streaming
VAD:
  FunASR:
    model: fsmn-vad

# 任何支持 openai sdk 的模型都可以使用
LLM:
  model: deepseek/deepseek-chat-v3-0324:free
  base_url: https://openrouter.ai/api/v1
  temperature: 0.7
  max_tokens: 1024
  streaming: true
  timeout: 20
