TTS:
  index_tts:
    config: checkpoints/checkpoints-config.yaml
  edge_tts:
    config: config/edge-tts.yaml
ASR:
  FunASR:
    model: FunAudioLLM/SenseVoiceSmall
    output_dir: tmp/
VAD:
  SileroVAD:
    sampling_rate: 16000
    threshold: 0.5
    min_silence_duration_ms: 200

# 任何支持 openai sdk 的模型都可以使用
LLM:
  model: deepseek/deepseek-chat-v3-0324:free
  base_url: https://openrouter.ai/api/v1
  temperature: 0.7
  max_tokens: 1024
  streaming: true
  timeout: 
